version: '3'

services:
  app:
    build: ./forecast_report
    image: forecast_report
    networks:
      - forecast-service-network
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./forecast_report/src:/app

  scraper:
      build: ./scraper
      image: scraper
      networks:
        - forecast-service-network
      env_file:
        - .env
      depends_on:
        db:
          condition: service_healthy
      volumes:
        - ./scraper/src:/app

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: forecast
      MYSQL_ROOT_PASSWORD: invista
      MYSQL_USER: invista
      MYSQL_PASSWORD: invista
      MYSQL_ROOT_HOST: '%'
    command: mysqld --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - "3306:3306"
    networks:
      - forecast-service-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - forecast-data:/var/lib/mysql

networks:
  forecast-service-network:
    driver: bridge

volumes:
  forecast-data:
