version: '3'

services:
  app:
    build: ./forecast_report
    image: forecast_report
    networks:
      - forecast-service-network
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./forecast_report/src:/app

  scraper:
      build: ./scraper
      image: scraper
      networks:
        - forecast-service-network
      env_file:
        - .env
      depends_on:
        - db
      links:
        - db
      volumes:
        - ./scraper/src:/app
      ports:
        - 5001:5000

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: forecast
      MYSQL_ROOT_PASSWORD: invista
      MYSQL_USER: invista
      MYSQL_PASSWORD: invista
      MYSQL_ROOT_HOST: '%'
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    networks:
      - forecast-service-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - forecast-data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_management
    ports:
      - 25672:25672
      - 15672:15672
    volumes:
      - /docker_conf/rabbitmq/data/:/var/lib/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "passw123"
    networks:
      - forecast-service-network
    restart: always

networks:
  forecast-service-network:

volumes:
  forecast-data:
