version: '3'

services:
  app:
    build: ./forecast_report
    image: forecast_report
    networks:
      - forecast-service-network
    depends_on:
      - db
    links:
      - db
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
    volumes:
      - ./forecast_report/src:/app

  scrapper:
      build: ./scrapper
      image: scrapper
      networks:
        - forecast-service-network
      depends_on:
        - db
      links:
        - db
      volumes:
        - ./scrapper/src:/app

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: forecast
      MYSQL_ROOT_PASSWORD: invista
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - "3306:3306"
    networks:
      - forecast-service-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - forecast-data:/var/lib/mysql

networks:
  forecast-service-network:

volumes:
  forecast-data:
